version: '3.5'

services:
  meemo-service:
    image: meinjens/meemo-service:latest
    networks:
      - traefik_public
      - consul_net
      - mariadb_net
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - traefik.http.services.meemo.loadbalancer.server.port=8080
        - traefik.http.routers.meemo.entryPoints=web
        - traefik.http.routers.meemo.service=productrepository
        - traefik.http.routers.meemo.rule=Host(`meemo.diemeineckes.de`)

networks:
  traefik_public:
    external: true
  consul_net:
    external: true
  mariadb_net:
    external: true
