version: '3.5'

services:
  meemo-service:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example