openapi: 3.0.2
servers:
  - url: 'http://localhost:8080/v1'
info:
  description: >-
    Campaign API
  version: 1.0.0
  title: Campaign Service
  contact:
    email: mail@jensmeinecke.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: campaign
    description: Operations about campaign
paths:
  /campaigns:
    get:
      summary: 'Get list of campaigns'
      description: ''
      parameters:
        - name: limit
          in: query
          description: Limit number of records returning
          required: false
          schema:
            type: integer
            format: int32
      operationId: getCampaigns
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/CampaignGetResponse'
    post:
      summary: 'Create campaign'
      description: ''
      operationId: createCampaign
      tags:
        - campaign
      requestBody:
        description: Campaign to create
        $ref: '#/components/requestBodies/CampaignCreateRequest'
      responses:
        '201':
          description: Campaign created (null response).
        default:
          description: Unexpected error
          $ref: '#/components/responses/ErrorResponse'

  /campaigns/{campaignId}:
    get:
      summary: 'Get campaign details'
      description: ''
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: getCampaign
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/CampaignGetResponse'
    put:
      summary: 'Update campaign details'
      description: ''
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: updateCampaign
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/CampaignGetResponse'
    delete:
      summary: 'Delete campaign details'
      description: ''
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: removeCampaign
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/CampaignGetResponse'

components:
  requestBodies:
    CampaignCreateRequest:
      description: OK
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Campaign'
  responses:
    CampaignGetResponse:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Campaign'
    CampaignListResponse:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Campaign'
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Campaign:
      type: object
      properties:
        id:
          type: string
          description: unique campaign id
        name:
          type: string
          description: name of the campaign

  securitySchemes: {}
  links: {}
  callbacks: {}
security: []
