openapi: 3.0.2
servers:
  - url: 'http://localhost:8080/v1'
info:
  title: Meemo Service API
  description: >-
    Services controlling meemo
  version: 1.0.0
  contact:
    name: Jens Meinecke
    email: mail@jensmeinecke.de
    url: https://jensmeinecke.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: campaigns
    description: Operations about campaign
  - name: items
    description: Operations about items of a campaign
  - name: versions
    description: Operations about versions of items

paths:
  /campaigns:
    get:
      summary: 'Get list of campaigns'
      description: ''
      operationId: getCampaigns
      tags:
        - campaigns
      parameters:
        - name: limit
          in: query
          description: Limit number of records returning
          required: false
          schema:
            type: integer
            format: int32
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    post:
      summary: 'Create campaign'
      description: ''
      operationId: createCampaign
      tags:
        - campaigns
      requestBody:
        description: Campaign to create
        $ref: '#/components/requestBodies/CampaignCreateRequest'
      responses:
        '201':
          description: Campaign created (null response).
        default:
          description: Unexpected error
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}:
    get:
      summary: 'Get campaign details'
      description: ''
      operationId: getCampaign
      tags:
        - campaigns
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      responses:
        default:
          $ref: '#/components/responses/CampaignGetResponse'
    put:
      summary: 'Update campaign details'
      description: ''
      operationId: updateCampaign
      tags:
        - campaigns
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    delete:
      summary: 'Delete campaign'
      description: ''
      operationId: removeCampaign
      tags:
        - campaigns
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}/duplicate:
    post:
      summary: 'Duplicate campaign with all its data'
      description: ''
      operationId: duplicateCampaign
      tags:
        - campaigns
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}/archive:
    post:
      summary: 'Move campaign to archive'
      description: ''
      operationId: archiveCampaign
      tags:
        - campaigns
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}/unarchive:
    post:
      summary: 'Unarchive campaign'
      description: ''
      operationId: unarchiveCampaign
      tags:
        - campaigns
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'

  /campaigns/{campaignId}/items:
    get:
      summary: 'Get list of campaign items'
      description: ''
      operationId: getItems
      tags:
        - items
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    post:
      summary: 'Create campaign item'
      description: ''
      operationId: createItem
      tags:
        - items
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      requestBody:
        description: Item to create
        $ref: '#/components/requestBodies/ItemCreateRequest'
      responses:
        '201':
          description: Campaign item created (null response).
        default:
          description: Unexpected error
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}/items/{itemId}:
    get:
      summary: 'Get campaign item details'
      description: ''
      operationId: getItem
      tags:
        - items
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Unique item identifier
          required: true
          schema:
            type: integer
            format: int32
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    put:
      summary: 'Update campaign item details'
      description: ''
      operationId: updateItem
      tags:
        - items
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Unique item identifier
          required: true
          schema:
            type: integer
            format: int32
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    delete:
      summary: 'Delete campaign item details'
      description: 'Removes an campaign from a campaign with all its data (voting, feedback etc.)'
      operationId: removeItem
      tags:
        - items
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Unique item identifier
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Campaign item deleted (null response).
        '404':
          description: Campaign item not found.
        default:
          $ref: '#/components/responses/ErrorResponse'

  /campaigns/{campaignId}/items/{itemId}/versions:
    get:
      summary: 'Get all versions of a campaign item'
      description: ''
      operationId: getVersions
      tags:
        - versions
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: integer
            format: int32
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    post:
      summary: 'Create campaign item version'
      description: ''
      operationId: createVersion
      tags:
        - versions
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Item to create
        $ref: '#/components/requestBodies/VersionCreateRequest'
      responses:
        '201':
          description: Campaign item version created (null response).
        default:
          description: Unexpected error
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}/items/{itemId}/versions/{version}:
    get:
      summary: 'Get a version of a campaign item'
      description: ''
      operationId: getVersion
      tags:
        - versions
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: integer
            format: int32
        - name: version
          in: path
          description: Unique version identifier
          required: true
          schema:
            type: integer
            format: int32
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    put:
      summary: 'Update a version of a campaign item'
      description: ''
      operationId: updateVersion
      tags:
        - versions
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: integer
            format: int32
        - name: version
          in: path
          description: Unique version identifier
          required: true
          schema:
            type: integer
            format: int32
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    delete:
      summary: 'Delete a version of a campaign item'
      description: ''
      operationId: deleteVersion
      tags:
        - versions
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: integer
            format: int32
        - name: version
          in: path
          description: Unique version identifier
          required: true
          schema:
            type: integer
            format: int32
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'


components:
  requestBodies:
    CampaignCreateRequest:
      description: Campaign to create
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Campaign'
    ItemCreateRequest:
      description: Create campaign item
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Item'
    VersionCreateRequest:
      description: Create campaign item version
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Version'

  responses:
    CampaignGetResponse:
      description: Campaign details
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Campaign'
    CampaignListResponse:
      description: List of campaigns
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Campaign'
    ErrorResponse:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Campaign:
      type: object
      properties:
        id:
          type: string
          description: Unique campaign id
        name:
          type: string
          description: Name of the campaign
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Unique item identifier
        name:
          type: string
          description: Caption of the campaign item
    Version:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Unique version identifier
        comment:
          type: string
          description: Comment on this version

  securitySchemes: {}
  links: {}
  callbacks: {}
security: []
