openapi: 3.0.2
servers:
  - url: 'http://localhost:8080/v1'
info:
  description: >-
    Campaign API
  version: 1.0.0
  title: Campaign Service
  contact:
    email: mail@jensmeinecke.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: campaign
    description: Operations about campaign
  - name: item
    description: Operations about items of a campaign

paths:
  /campaigns:
    get:
      summary: 'Get list of campaigns'
      description: ''
      parameters:
        - name: limit
          in: query
          description: Limit number of records returning
          required: false
          schema:
            type: integer
            format: int32
      operationId: getCampaigns
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    post:
      summary: 'Create campaign'
      description: ''
      operationId: createCampaign
      tags:
        - campaign
      requestBody:
        description: Campaign to create
        $ref: '#/components/requestBodies/CampaignCreateRequest'
      responses:
        '201':
          description: Campaign created (null response).
        default:
          description: Unexpected error
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}:
    get:
      summary: 'Get campaign details'
      description: ''
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: getCampaign
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/CampaignGetResponse'
    put:
      summary: 'Update campaign details'
      description: ''
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: updateCampaign
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    delete:
      summary: 'Delete campaign'
      description: ''
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: removeCampaign
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}/archive:
    post:
      summary: 'Move campaign to archive'
      description: ''
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: archiveCampaign
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
  /campaigns/{campaignId}/unarchive:
    post:
      summary: 'Unarchive campaign'
      description: ''
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: unarchiveCampaign
      tags:
        - campaign
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'

  /campaigns/{campaignId}/items:
    get:
      summary: 'Get list of campaign items'
      description: ''
      tags:
        - item
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      operationId: getItems
      responses:
        default:
          $ref: '#/components/responses/ErrorResponse'
    post:
      summary: 'Create campaign item'
      description: ''
      tags:
        - item
      operationId: createItem
      parameters:
        - name: campaignId
          in: path
          description: Unique campaign identifier
          required: true
          schema:
            type: string
      requestBody:
        description: Item to create
        $ref: '#/components/requestBodies/ItemCreateRequest'
      responses:
        '201':
          description: Campaign item created (null response).
        default:
          description: Unexpected error
          $ref: '#/components/responses/ErrorResponse'




components:
  requestBodies:
    CampaignCreateRequest:
      description: Campaign to create
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Campaign'
    ItemCreateRequest:
      description: Create campaign item
      required: trie
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Item'
  responses:
    CampaignGetResponse:
      description: Campaign details
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Campaign'
    CampaignListResponse:
      description: List of campaigns
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Campaign'
    ErrorResponse:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Campaign:
      type: object
      properties:
        id:
          type: string
          description: unique campaign id
        name:
          type: string
          description: name of the campaign
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: unique item identifier
        name:
          type: string
          description: caption of the campaign item

  securitySchemes: {}
  links: {}
  callbacks: {}
security: []
